## Simulation Mode 
solution_mode: 'snapshot' # 0 snapshot (annual peak load) | 1 daily | 2 yearly [more modes here: https://opendss.epri.com/Mode2.html]

line_rating_mode: 'heat_balance_linear_proxy' # heat_balance_linear_proxy uses heat-balance eq. to find %/C linear relationship between SMART-DS default ampacity (assumed to be set for near_worst_temp, e.g., p99) and real-timetemp
transformers_rating_mode: 'ieee_linear_proxy' # linear conservative approximation from IEEE 738

  
TGW_years_scenarios:
  '2018': ["historical"]
  '2058': ["rcp45cooler", "rcp45hotter", "rcp85cooler", "rcp85hotter"]


# ## all regions
CITY_REGIONS_TO_RUN:
   AUS: ["P1R", "P1U", "P2U"]
   GSO: ["rural", "industrial", "urban-suburban"]
   SFO: ["P1U", "P2U", "P1R"]
   

smart_ds_years:
  - "2018"
  
# start and end months for selecting top city demand mdh
start_month_mdh: 6
end_month_mdh: 9
# define % of hours of the year ( round(8760*top_percent_mdh/100) )
start_row_percent: 0 # define percentage of last run to avoid running same mdh again, e.g., start_row_percent = 1 and top_percent_mdh = 10 means that loop will start from the 99th percentile hours and continue until the 90th percentile 
top_percent_mdh: 20

  
  
## Load prediction 
aggregation_level: "feeder"  # building | feeder | regional
#### Model training/prediction paramaters ####
Y_column: "cooling_kw_sum"  # output label options:  total_site_electricity_kw | cooling_kw | cooling_kw_sum | heating_kw | 
X_columns_set: "X_columns_D" # default option. input features options: X_columns_A (time+weather) | X_columns_B (only high corr weather) | X_columns_C (only temp) | X_columns_D (additional features)
demand_mode: 'MLP' # MLP | linear | none
# Define months for training: load and weather data (inclusive)
start_month: 1
end_month: 12
# Define building types to loop over
building_types: ["res", "com"]


## Define paths
input_data_dict_name: "input_data_dict_proc" # input_data_dict_proc -  Input data with additional features and without redundant features | 'input_data_dict' - Raw data with minimal processing
# Define default paths for saving/loading input and output data (path is updated by function for the correct months and aggregation level)
input_data_training_path: "main_folder/load_prediction/results/data/training/2018/months_6_8/ml_input_data/resstock/amy2018/regional/" 
output_data_training_path: "main_folder/load_prediction/results/data/training/2018/months_6_8/ml_output_data/total_site_electricity_kw/regional/" 
input_data_prediction_path: "main_folder/load_prediction/results/data/prediction/input/TGW_weather/Concord/Historical/" 
output_data_prediction_path: "main_folder/load_prediction/results/data/prediction/output/2018/months_1_12/heating_kw/feature_A/regional/all_regions" 
smart_ds_load_path: "main_folder/load_prediction/results/data/smart_ds_load"
output_pf_path: "main_folder/OpenDSS/results/data/network_performance" 

